services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: lab3_user
      POSTGRES_PASSWORD: lab3_user_password
    ports:
      - "5432:5432"

